def summ(num1, num2):
    try:
        return num1 + num2
    except(Exception):
        return "Ошибка."
